---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
      interval: 12h
  values:
    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
      websecure:
        tls:
          enabled: true
      metrics:
        port: 9100
        expose:
          default: true
        exposedPort: 9100
        protocol: TCP

    ingressRoute:
      dashboard:
        enabled: true
        annotations: {}
        labels: {}
        matchRule: Host(`traefik.malachowski.me`)
        entryPoints: ["websecure"]
        middlewares: []
        tls: {}

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-lb
        allowCrossNamespace: true
        allowExternalNameServices: true
        namespaces: []
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: false
        ingressClass: traefik-lb
        namespaces: []
        publishedService:
          enabled: false

    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--entrypoints.websecure.forwardedheaders.trustedips=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
      - "--entrypoints.web.forwardedheaders.trustedips=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
      - "--api.insecure=true"
      - "--entrypoints.websecure.http.tls.options=default"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"

    env: []

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec: {}
      loadBalancerSourceRanges: []
      externalIPs: []

    autoscaling:
      enabled: false

    persistence:
      enabled: false

    certResolvers: {}

    # Remove experimental plugins to avoid configuration errors

    affinity: {}

    nodeSelector: {}

    tolerations: []

    topologySpreadConstraints: []

    priorityClassName: ""

    securityContext:
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532

    podSecurityContext:
      fsGroup: 65532
