---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default'
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
    
    receivers:
      - name: 'null'
      - name: 'default'
        webhook_configs:
          - url: 'http://localhost:9093/api/v1/alerts'
            send_resolved: true
    
    templates: []
