---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-stack.yaml
  - loki-stack.yaml
  - alertmanager-config.yaml
  # IngressRoutes will be created after Traefik CRDs are available
