---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-stack.yaml
  - ingress-routes.yaml
  - loki-stack.yaml
  - alertmanager-config.yaml
  # ServiceMonitor for Traefik will be created after Prometheus Operator is ready
