name: gitleaks

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 4 AM UTC

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
